# SVM

In [1]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.svm import SVR

In [2]:
X = [[0, 0], [1, 1]]
y = [0, 1]

In [3]:
clf = SVC(probability = True)
clf.fit(X, y)

SVC()

SVC()

In [4]:
clf.fit_status_

0

In [5]:
clf.predict([[2., 2.]])

array([1])

In [6]:
clf.predict_proba([[2., 2.]])

array([[0.5, 0.5]])

In [7]:
clf.predict([[-1, -1]])

array([0])

In [8]:
clf.predict_proba([[-1, -1]])

array([[0.5, 0.5]])

In [9]:
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [10]:
clf.support_

array([0, 1], dtype=int32)

In [11]:
clf.n_support_

array([1, 1], dtype=int32)

## SVC with Pipeline

In [12]:
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])

In [13]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [14]:
clf.predict([[-0.8, -1]])

array([1])

In [15]:
clf.steps[1]

('svc', SVC(gamma='auto'))

## Multi-class classification using SVC

In [38]:
X = [[0], [1], [2], [3]]
Y = [0, 1, 2, 3]

In [39]:
clf = SVC(probability = True, decision_function_shape='ovo')
clf.fit(X, Y)

SVC(decision_function_shape='ovo', probability=True)

In [40]:
clf.fit_status_

0

In [41]:
clf.predict_proba([[1.5], [2.5]])

array([[0.30555808, 0.1945267 , 0.19424954, 0.30566567],
       [0.32935651, 0.29521955, 0.18775367, 0.18767027]])

In [42]:
clf.predict([[1.5], [2.5]])

array([2, 3])

In [21]:
SVC(decision_function_shape='ovo')
dec = clf.decision_function([[1]])
dec.shape[1] # 4 classes: 4*3/2 = 6

6

In [22]:
clf.decision_function_shape = "ovr"
dec = clf.decision_function([[1]])
dec.shape[1] # 4 classes

4

## Support Vector Regression (SVR)

In [23]:
from sklearn.svm import SVR

In [24]:
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]

In [25]:
regr = SVR()
regr.fit(X, y)
regr.predict([[1, 1]])

array([1.5])

In [26]:
regr.predict([[1.5, 1.5]])

array([2.11736891])

In [27]:
regr.predict([[3.5, 2.5]])

array([1.76257708])

In [28]:
regr.fit_status_

0

## Support Vector Regression (SVR) on Random Data

In [29]:
n_samples, n_features = 10, 5
rng = np.random.RandomState(0)

In [30]:
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
X_test = rng.randn(n_samples//2, n_features)
y_test = rng.randn(n_samples//2)

In [31]:
(X, y)

(array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
        [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
        [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
        [-1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
        [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
        [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
        [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218],
        [-0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028],
        [-0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223],
        [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117]]),
 array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ]))

In [32]:
regr = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2))
regr.fit(X, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(epsilon=0.2))])

In [33]:
X_test, y_test

(array([[-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614],
        [-0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.0519454 ],
        [ 0.72909056,  0.12898291,  1.13940068, -1.23482582,  0.40234164],
        [-0.68481009, -0.87079715, -0.57884966, -0.31155253,  0.05616534],
        [-1.16514984,  0.90082649,  0.46566244, -1.53624369,  1.48825219]]),
 array([ 1.89588918,  1.17877957, -0.17992484, -1.07075262,  1.05445173]))

In [34]:
regr.predict(X_test)

array([0.56730899, 0.21981431, 0.48469761, 0.55606509, 0.80520213])

In [35]:
regr.score(X_test, y_test)

-0.03872504270664212

## Scaling

In [36]:
clf = make_pipeline(StandardScaler(), SVC())